language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install ."
  - "pip install -r requirements-dev.txt"
script:
  - "flake8 tit.py setup.py"
  - "tit --help"  # testing it's executable...
